// Kategori ve alt kategori verileri — tüm uygulamada ortak kullanılır

export type SubCategory = { label: string; slug: string };
export type Category = { label: string; slug: string; subcategories: SubCategory[] };

export const CATEGORIES: Category[] = [
  {
    label: "Elektronik", slug: "elektronik",
    subcategories: [
      { label: "Cep Telefonu", slug: "cep-telefonu" },
      { label: "Kılıf & Koruyucu", slug: "kilif-koruyucu" },
      { label: "Şarj Aleti & Kablo", slug: "sarj-aleti" },
      { label: "Kulaklık", slug: "kulaklik" },
      { label: "Powerbank", slug: "powerbank" },
      { label: "Akıllı Saat", slug: "akilli-saat" },
      { label: "Laptop", slug: "laptop" },
      { label: "Tablet", slug: "tablet" },
      { label: "Monitör", slug: "monitor" },
      { label: "Klavye & Mouse", slug: "klavye-mouse" },
      { label: "SSD & Bellek", slug: "ssd-bellek" },
      { label: "Akıllı TV", slug: "akilli-tv" },
      { label: "Soundbar & Hoparlör", slug: "soundbar" },
      { label: "Oyun Konsolu", slug: "oyun-konsolu" },
      { label: "Oyun Kolu & Aksesuar", slug: "oyun-kolu" },
      { label: "VR Gözlük", slug: "vr-gozluk" },
      { label: "Drone", slug: "drone" },
      { label: "Fotoğraf Makinesi", slug: "fotograf-makinesi" },
    ],
  },
  {
    label: "Giyim & Moda", slug: "giyim-aksesuar",
    subcategories: [
      { label: "Kadın Elbise", slug: "kadin-elbise" },
      { label: "Kadın Bluz & Gömlek", slug: "kadin-bluz" },
      { label: "Kadın Pantolon & Tayt", slug: "kadin-pantolon" },
      { label: "Kadın Etek", slug: "kadin-etek" },
      { label: "Kadın Mont & Kaban", slug: "kadin-mont" },
      { label: "Kadın İç Giyim & Pijama", slug: "kadin-ic-giyim" },
      { label: "Erkek T-shirt & Polo", slug: "erkek-tshirt" },
      { label: "Erkek Gömlek", slug: "erkek-gomlek" },
      { label: "Erkek Pantolon & Jean", slug: "erkek-pantolon" },
      { label: "Erkek Sweatshirt & Hoodie", slug: "erkek-sweatshirt" },
      { label: "Erkek Takım Elbise", slug: "erkek-takim" },
      { label: "Erkek Mont & Yelek", slug: "erkek-mont" },
      { label: "Kız Çocuk Giyim", slug: "kiz-cocuk" },
      { label: "Erkek Çocuk Giyim", slug: "erkek-cocuk" },
      { label: "Bebek Kıyafeti", slug: "bebek-kiyafeti" },
      { label: "Spor Ayakkabı", slug: "spor-ayakkabi" },
      { label: "Topuklu Ayakkabı", slug: "topuklu-ayakkabi" },
      { label: "Bot & Çizme", slug: "bot-cizme" },
      { label: "El Çantası", slug: "el-cantasi" },
      { label: "Sırt Çantası", slug: "sirt-cantasi" },
      { label: "Cüzdan & Aksesuar", slug: "cuzdan" },
    ],
  },
  {
    label: "Ev & Yaşam", slug: "ev-dekorasyonu",
    subcategories: [
      { label: "Koltuk & Kanepe", slug: "koltuk" },
      { label: "Yatak & Yatak Odası", slug: "yatak-odasi" },
      { label: "Yemek Odası Takımı", slug: "yemek-odasi" },
      { label: "Çalışma Masası & Sandalye", slug: "calisma-masasi" },
      { label: "Gardırop & Dolap", slug: "gardirop" },
      { label: "Raf & Kitaplık", slug: "raf-kitaplik" },
      { label: "Tablo & Duvar Sanatı", slug: "tablo" },
      { label: "Vazo & Saksı", slug: "vazo-saksi" },
      { label: "Mum & Mumluk", slug: "mum-mumluk" },
      { label: "Ayna", slug: "ayna" },
      { label: "Halı & Kilim", slug: "hali-kilim" },
      { label: "Yastık & Örtü", slug: "yastik-ortu" },
      { label: "Tencere & Tava", slug: "tencere-tava" },
      { label: "Kahve & Çay Ekipmanları", slug: "kahve-cay" },
      { label: "Küçük Ev Aletleri", slug: "kucuk-ev-aletleri" },
      { label: "Banyo Seti & Aksesuar", slug: "banyo-seti" },
      { label: "Avize & Lamba", slug: "avize-lamba" },
      { label: "LED Aydınlatma", slug: "led-aydinlatma" },
      { label: "Bahçe Mobilyası", slug: "bahce-mobilyasi" },
      { label: "Bahçe & Bitki", slug: "bahce-bitki" },
    ],
  },
  {
    label: "Spor & Outdoor", slug: "spor",
    subcategories: [
      { label: "Koşu Ayakkabısı", slug: "kosu-ayakkabisi" },
      { label: "Spor Giyim", slug: "spor-giyim" },
      { label: "Fitness & Gym Ekipmanı", slug: "fitness-gym" },
      { label: "Yoga & Pilates", slug: "yoga-pilates" },
      { label: "Protein & Takviye", slug: "protein-takviye" },
      { label: "Outdoor & Kamp", slug: "outdoor-kamp" },
      { label: "Trekking & Dağcılık", slug: "trekking" },
      { label: "Bisiklet & Aksesuar", slug: "bisiklet" },
      { label: "Yüzme & Su Sporları", slug: "yuzme-su-sporlari" },
      { label: "Kayak & Kış Sporları", slug: "kayak" },
      { label: "Futbol", slug: "futbol" },
      { label: "Basketbol & Voleybol", slug: "basketbol-voleybol" },
      { label: "Tenis & Padel", slug: "tenis-padel" },
    ],
  },
  {
    label: "Kitap & Hobi", slug: "kitap",
    subcategories: [
      { label: "Roman & Edebiyat", slug: "roman-edebiyat" },
      { label: "Kişisel Gelişim", slug: "kisisel-gelisim" },
      { label: "Çocuk Kitapları", slug: "cocuk-kitaplari" },
      { label: "Ders & Kaynak Kitap", slug: "ders-kaynak" },
      { label: "Biyografi & Tarih", slug: "biyografi-tarih" },
      { label: "Gitar & Aksesuar", slug: "gitar" },
      { label: "Piyano & Org", slug: "piyano-org" },
      { label: "Davul & Perküsyon", slug: "davul" },
      { label: "Keman & Yaylı Saz", slug: "keman" },
      { label: "Boyama & Resim Seti", slug: "boyama-resim" },
      { label: "El İşi & Dikiş & Örgü", slug: "el-isi-dikis" },
      { label: "Seramik & Heykel", slug: "seramik-heykel" },
      { label: "Kutu Oyunu & Puzzle", slug: "kutu-oyunu" },
      { label: "Satranç & Strateji", slug: "satranc" },
      { label: "Koleksiyon & Figür", slug: "koleksiyon-figur" },
    ],
  },
  {
    label: "Anne & Bebek", slug: "bebek",
    subcategories: [
      { label: "Yenidoğan Kıyafeti (0-3 Ay)", slug: "yenidogan-kiyafet" },
      { label: "Bebek Kıyafeti (3-12 Ay)", slug: "bebek-kiyafeti-3-12" },
      { label: "Toddler Kıyafet (1-3 Yaş)", slug: "toddler-kiyafet" },
      { label: "Bebek Arabası", slug: "bebek-arabasi" },
      { label: "Ana Kucağı & Taşıyıcı", slug: "ana-kucagi" },
      { label: "Bebek Karyolası & Beşik", slug: "bebek-karyolasi" },
      { label: "Oto Koltuğu", slug: "oto-koltugu" },
      { label: "Mama Sandalyesi", slug: "mama-sandalyesi" },
      { label: "Biberon & Emzik", slug: "biberon-emzik" },
      { label: "Bebek Maması & Gıda", slug: "bebek-mamasi" },
      { label: "Bez & Islak Mendil", slug: "bez-islak-mendil" },
      { label: "Bebek Bakım & Kozmetik", slug: "bebek-bakim" },
      { label: "Eğitici Oyuncak", slug: "egitici-oyuncak" },
      { label: "Ahşap Oyuncak", slug: "ahsap-oyuncak" },
      { label: "Bebek Monitörü", slug: "bebek-monitoru" },
    ],
  },
  {
    label: "Mücevher & Saat", slug: "mucevher",
    subcategories: [
      { label: "Altın Kolye", slug: "altin-kolye" },
      { label: "Altın Bilezik & Kelepçe", slug: "altin-bilezik" },
      { label: "Altın Yüzük", slug: "altin-yuzuk" },
      { label: "Altın Küpe", slug: "altin-kupe" },
      { label: "Gümüş Kolye", slug: "gumus-kolye" },
      { label: "Gümüş Bileklik & Yüzük", slug: "gumus-bileklik" },
      { label: "Gümüş Küpe", slug: "gumus-kupe" },
      { label: "Pırlanta & Elmas Takı", slug: "pirlanta" },
      { label: "Swarovski & Kristal", slug: "swarovski" },
      { label: "İnci & Doğaltaş", slug: "inci-dogaltas" },
      { label: "Erkek Saati", slug: "erkek-saati" },
      { label: "Kadın Saati", slug: "kadin-saati" },
      { label: "Akıllı Saat & Bileklik", slug: "akilli-saat-bileklik" },
      { label: "Saat Kordonu & Aksesuar", slug: "saat-kordonu" },
    ],
  },
  {
    label: "Süpermarket", slug: "market",
    subcategories: [
      { label: "Bakliyat & Tahıl", slug: "bakliyat-tahil" },
      { label: "Makarna & Pirinç", slug: "makarna-pirinc" },
      { label: "Atıştırmalık & Çerez", slug: "atistirmalik" },
      { label: "Çay & Kahve", slug: "cay-kahve" },
      { label: "Meyve Suyu & İçecek", slug: "icecek" },
      { label: "Doğal & Organik Gıda", slug: "dogal-organik" },
      { label: "Şampuan & Saç Bakımı", slug: "sampuan-sac" },
      { label: "Cilt Bakımı & Nemlendirici", slug: "cilt-bakimi" },
      { label: "Diş Bakımı", slug: "dis-bakimi" },
      { label: "Parfüm & Deodorant", slug: "parfum-deodorant" },
      { label: "Deterjan & Çamaşır", slug: "deterjan-camasir" },
      { label: "Yüzey Temizleyici", slug: "yuzey-temizleyici" },
      { label: "Kağıt Ürünleri", slug: "kagit-urunleri" },
      { label: "Kedi Ürünleri", slug: "kedi-urunleri" },
      { label: "Köpek Ürünleri", slug: "kopek-urunleri" },
      { label: "Kuş & Balık & Diğer", slug: "diger-evcil-hayvan" },
    ],
  },
  {
    label: "Otomotiv", slug: "otomotiv",
    subcategories: [
      { label: "Araç Telefon Tutucu", slug: "arac-tutucu" },
      { label: "Dash Cam (Araç Kamerası)", slug: "dash-cam" },
      { label: "Araç Şarj Aleti", slug: "arac-sarj" },
      { label: "Araç Koltuk Kılıfı & Minderi", slug: "arac-koltuk" },
      { label: "Araç Koku & Aksesuar", slug: "arac-koku" },
      { label: "Yaz Lastiği", slug: "yaz-lastigi" },
      { label: "Kış Lastiği", slug: "kis-lastigi" },
      { label: "Jant & Aksesuar", slug: "jant" },
      { label: "Motor Yağı & Bakım", slug: "motor-yagi" },
      { label: "Fren & Süspansiyon", slug: "fren-suspansiyon" },
      { label: "Far & Stop & Sinyal", slug: "far-stop" },
      { label: "Silecek & Cam Sistemi", slug: "silecek-cam" },
      { label: "Akü & Elektrik", slug: "aku-elektrik" },
      { label: "Motosiklet Kaskı", slug: "motosiklet-kaski" },
      { label: "Motosiklet Giyim & Ekipman", slug: "motosiklet-giyim" },
    ],
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function getSubcategoryLabel(catSlug: string, subSlug: string): string {
  const cat = getCategoryBySlug(catSlug);
  return cat?.subcategories.find((s) => s.slug === subSlug)?.label ?? subSlug;
}
