-- Örnek zanaatkarlar ekleme
INSERT INTO users (email, full_name, role, bio, location, phone) VALUES
('ayse@ornek.com', 'Ayşe Hanım Atölyesi', 'artisan', 'Geleneksel el dokuması kilim ve halı yapımında 30 yıllık deneyim. Anadolu motiflerini modern tasarımlarla buluşturuyorum.', 'Gaziantep, Türkiye', '+90 555 111 2233'),
('mehmet@ornek.com', 'Marangoz Mehmet', 'artisan', 'Doğal ahşap işleme sanatında ustayım. Her ürün özenle seçilmiş masif ahşaplardan üretilir.', 'Bolu, Türkiye', '+90 555 222 3344'),
('zeynep@ornek.com', 'Çömlek Sanatı', 'artisan', 'Seramik ve çömlek yapımında geleneksel teknikleri kullanıyorum. Her parça fırında pişirilerek özel olarak hazırlanır.', 'Avanos, Türkiye', '+90 555 333 4455'),
('fatma@ornek.com', 'Gümüş Atölye', 'artisan', 'El yapımı gümüş takı tasarımı. Geleneksel Türk motifleri ile modern çizgileri harmanlıyorum.', 'İstanbul, Türkiye', '+90 555 444 5566'),
('ali@ornek.com', 'Deri Ustası Ali', 'artisan', 'Hakiki deri işleme ve çanta yapımı. Her ürün el dikişi ile özenle hazırlanır.', 'İzmir, Türkiye', '+90 555 555 6677');

-- Örnek ürünler ekleme
INSERT INTO products (artisan_id, name, description, price, category, stock, images, customizable, tags) VALUES
-- Ev Dekorasyonu
((SELECT id FROM users WHERE email = 'ayse@ornek.com'), 
'El Dokuma Kilim Yastık', 
'Geleneksel Anadolu motifleriyle süslenmiş el dokuması kilim yastık. 45x45 cm boyutunda, içi dahil. Doğal yün iplik kullanılmıştır.',
125.00,
'ev-dekorasyonu',
15,
ARRAY['/placeholder.svg?height=800&width=800'],
true,
ARRAY['kilim', 'yastık', 'el dokuma', 'yeni']),

((SELECT id FROM users WHERE email = 'mehmet@ornek.com'),
'El Yapımı Ahşap Tepsi',
'Ceviz ağacından üretilmiş, doğal ahşap tepsi. 50x30 cm boyutunda. Su bazlı vernik ile korunmuştur. Kahvaltı ve ikram sunumları için ideal.',
156.00,
'ev-dekorasyonu',
8,
ARRAY['/placeholder.svg?height=800&width=800'],
true,
ARRAY['ahşap', 'tepsi', 'ceviz', 'öne çıkan']),

((SELECT id FROM users WHERE email = 'zeynep@ornek.com'),
'Seramik Vazo - Turkuaz',
'El yapımı seramik vazo. Turkuaz sır ile kaplanmış, fırında 1200°C'de pişirilmiştir. Yükseklik: 25cm, Çap: 15cm.',
89.00,
'ev-dekorasyonu',
12,
ARRAY['/placeholder.svg?height=800&width=800'],
false,
ARRAY['seramik', 'vazo', 'turkuaz', 'popüler']),

((SELECT id FROM users WHERE email = 'mehmet@ornek.com'),
'Ahşap Duvar Saati',
'Masif meşe ağacından üretilmiş modern duvar saati. Çap: 30cm. Sessiz çalışan mekanizma dahildir.',
198.00,
'ev-dekorasyonu',
5,
ARRAY['/placeholder.svg?height=800&width=800'],
true,
ARRAY['ahşap', 'saat', 'meşe']),

-- El Sanatları
((SELECT id FROM users WHERE email = 'ayse@ornek.com'),
'Otantik El Dokuma Kilim',
'Geleneksel el tezgahında dokunmuş orijinal kilim. 120x180 cm boyutunda. Doğal boyalarla renklendirilmiş yün iplik.',
890.00,
'el-sanatlari',
3,
ARRAY['/placeholder.svg?height=800&width=800'],
true,
ARRAY['kilim', 'halı', 'el dokuma']),

((SELECT id FROM users WHERE email = 'zeynep@ornek.com'),
'Seramik Kahve Fincanı Seti',
'6 parça seramik kahve fincanı ve tabağı. El yapımı, her biri benzersiz. Bulaşık makinesinde yıkanabilir.',
245.00,
'el-sanatlari',
10,
ARRAY['/placeholder.svg?height=800&width=800'],
false,
ARRAY['seramik', 'fincan', 'set']),

-- Moda
((SELECT id FROM users WHERE email = 'fatma@ornek.com'),
'Özel Tasarım Kolye',
'925 ayar gümüşten üretilmiş özel tasarım kolye. Osmanlı motifi işlemeli. Zincir uzunluğu: 45cm.',
210.00,
'moda',
20,
ARRAY['/placeholder.svg?height=800&width=800'],
true,
ARRAY['gümüş', 'kolye', 'takı', 'kişiye özel']),

((SELECT id FROM users WHERE email = 'ali@ornek.com'),
'Hakiki Deri Omuz Çantası',
'Birinci sınıf hakiki deri omuz çantası. El dikişi detaylar. Boyutlar: 35x25x10 cm. Kahverengi ve siyah renk seçenekleri.',
445.00,
'moda',
7,
ARRAY['/placeholder.svg?height=800&width=800'],
true,
ARRAY['deri', 'çanta', 'omuz çantası']),

((SELECT id FROM users WHERE email = 'fatma@ornek.com'),
'Gümüş Küpe - Antik Desen',
'El işçiliği gümüş küpe. Antik Anadolu desenli. 925 ayar gümüş.',
167.00,
'moda',
15,
ARRAY['/placeholder.svg?height=800&width=800'],
false,
ARRAY['gümüş', 'küpe', 'takı']),

-- Hediyeler
((SELECT id FROM users WHERE email = 'mehmet@ornek.com'),
'Kişiye Özel İsimli Kaşık',
'Ahşap kaşık üzerine lazer gravür ile isim yazılır. Doğum günü, düğün hediyelik için ideal.',
45.00,
'hediyeler',
50,
ARRAY['/placeholder.svg?height=800&width=800'],
true,
ARRAY['ahşap', 'kaşık', 'hediye', 'kişiye özel']),

((SELECT id FROM users WHERE email = 'zeynep@ornek.com'),
'Seramik Kumbara',
'El yapımı seramik kumbara. Çocuklar için renkli ve eğlenceli tasarımlar.',
78.00,
'hediyeler',
25,
ARRAY['/placeholder.svg?height=800&width=800'],
false,
ARRAY['seramik', 'kumbara', 'çocuk']),

((SELECT id FROM users WHERE email = 'ayse@ornek.com'),
'Kilim Desenli Çerçeve',
'Kilim kumaş ile kaplanmış ahşap çerçeve. Fotoğraf ebatı: 15x20 cm.',
95.00,
'hediyeler',
18,
ARRAY['/placeholder.svg?height=800&width=800'],
false,
ARRAY['kilim', 'çerçeve', 'hediye']);

-- Ürünlere yorum ekleme
INSERT INTO reviews (product_id, user_id, rating, comment) VALUES
((SELECT id FROM products WHERE name = 'El Dokuma Kilim Yastık'), 
 (SELECT id FROM users WHERE email = 'mehmet@ornek.com'),
 5,
 'Harika bir ürün! Kalitesi çok yüksek ve evimize çok yakıştı. Ayşe Hanımın ellerine sağlık.'),

((SELECT id FROM products WHERE name = 'El Dokuma Kilim Yastık'),
 (SELECT id FROM users WHERE email = 'zeynep@ornek.com'),
 5,
 'Gerçekten el emeği göz nuru. Kargo da çok hızlı geldi. Teşekkürler!'),

((SELECT id FROM products WHERE name = 'Seramik Vazo - Turkuaz'),
 (SELECT id FROM users WHERE email = 'ayse@ornek.com'),
 5,
 'Rengi çok canlı ve işçiliği mükemmel. Salon masasında harika duruyor.'),

((SELECT id FROM products WHERE name = 'El Yapımı Ahşap Tepsi'),
 (SELECT id FROM users WHERE email = 'fatma@ornek.com'),
 5,
 'Ahşabın doğallığı ve kalitesi harika. Kahvaltılarımız artık daha keyifli!'),

((SELECT id FROM products WHERE name = 'Özel Tasarım Kolye'),
 (SELECT id FROM users WHERE email = 'ali@ornek.com'),
 5,
 'Eşime hediye aldım, çok beğendi. Gümüşün kalitesi belli oluyor.');
